### PR TITLE
Rk lindsey patch lmp

### PR DESCRIPTION
**Pull request by RKLindsey**
Fix traj_bad creation for runs using LAMMPS as the MD driver. 

Due to how LAMMPS runs are distrbuted, traj_bad files cannot be made the same way as in the ChIMES_MD code. In LAMMPS, each rank prints out a file indicating, for a given frame, the maximum "badness" of a that configuration. Based on these files and the traj.lammpstrj, the ALD creates the traj_bad files. 

Bookkeeping was incorrect in the previous version - this has been fixed.

### CODE REVIEW

**Comment by RKLindsey** [comment]
@vallabh-vasudevan  FYI, this should fix the issue you were having when using LAMMPS as a simulation driver regarding the traj_bad files, but not the triclinic cell issue.

**Comment by RKLindsey** [comment]
@S-A-Almohri Could you check out the merge conflict and let me know what you think? It looks like I have some lines that doesn't exist in the current develop version.

**Review by S-A-Almohri — CHANGES_REQUESTED** [review]
These changes were done on an older version and gen_ff.py should be reverted and updated to the current version before we can merge; suggestion for now is to pull the latest version then commit changes to gauss_driver.py, lmp_run_md.py and lmp_to_xyz.py; gen_ff.py will be updated in a later commit by me(@S-A-Almohri) fixing some lines as discussed with @Awwal41

**Comment by RKLindsey** [comment]
@S-A-Almohri Ok, conflict should be resolved!

**Review by S-A-Almohri — APPROVED** [review]
gen_ff.py has no issues that I can see and the rest look fine to me.

**Comment by RKLindsey** [comment]
@S-A-Almohri Are you able to review? See attached.
Screenshot 2024-10-25 at 3 49 22 PM

**Review by rk-lindsey — APPROVED** [review]

**Review by rk-lindsey — APPROVED** [review]

**Pull request merged**
